version: "3.9"

services:
  mina-graphql-api:
    container_name: mina-graphql-api
    build:
      context: .
      dockerfile: Dockerfile
    image: mina-graphql-api
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - "~/greenlock.d/:/usr/src/app/greenlock.d/"
